### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [hessnd/project11#1]
I can't seem to sign in on Heroku. Did you forget to create the user in that database?

**Comment by hessnd** [comment]
It was working fine up until class Monday.  I just added the user in again and it works when I run it locally but when I push it to heroku it wont let me log in.  Am I missing something I have to do with heroku?

**Comment by chrisvfritz** [comment]
Probably. Just like we run `heroku run rake db:migrate` to run `rake db:migrate` on Heroku, we have to run `heroku run rails console` to add the user to Heroku's `rails console`. Let me know if that helps!

**Comment by hessnd** [comment]
Ok got it fixed.  I'm sorry it took so long, I thought I had already fixed this error until I got the email today ha.

**Comment by chrisvfritz** [comment]
Much better. The only thing I see now that should be updated is an "Edit" link on the `show` page when not signed in. It should probably be hidden, as it is on the `index` page.

**Comment by hessnd** [comment]
Ok just fixed it.

**Comment by chrisvfritz** [comment]
:+1: Wonderful!
